### ISSUE TITLE
'riskeff' type ERROR

### ISSUE THREAD

**Issue by Lumpen95** [ArdiaD/RiskPortfolios#19]
Is the 'riskeff' type only able to calculate weights for **portfolios consisting of only 10 assets?** Looking at the code of the function, it seems to be configured that way. Is it possible to modify it to calculate weights with fewer assets than 10? Thanks for reading.

`  for (i in 2:11) {
    pos <- semiDev > pct[i - 1] & semiDev <= pct[i]
    J[pos, i - 1] <- 1
    epsilon[i - 1] <- median(semiDev[pos])
  }`

**Comment by ArdiaD** [comment]
It's iterating over the percentiles, not the number of stocks...

**Comment by Lumpen95** [comment]
I see you meant percentiles...but why doesn't it count if there are fewer than 10 assets? Can you take a look at the code? please....





packages <- c('quantmod', 'ggplot2', 'tidyverse', 'psych', 'PerformanceAnalytics', 'magrittr', 'timeSeries', 'RiskPortfolios')
lapply(packages, library, character.only = TRUE)

## 1. return data ------------------------------------------------------

ticker <- c('SPY', 'IWM', 'EFA', 'TLT')
portfolio_n <- length(ticker)
getSymbols(ticker)
prices <- do.call(cbind,
                  lapply(ticker, function(x) Ad(get(x)))) %>% 
  setNames(ticker)
rets <- Return.calculate(prices) %>% na.omit(.)
head(rets)

## cov-var matrix
covmat <- covEstimation(rets)
semiDev <- semidevEstimation(rets)

## 2. Optimal weights ---------------------------------------------------
opt_w <- optimalPortfolio(Sigma = covmat, semiDev = semiDev,
                          control = list(type = 'riskeff',
                                         constraint = 'lo')) %>% 
  round(., 4) %>% 
  setNames(colnames(rets)) %>% 
  print(.)

**Comment by ArdiaD** [comment]
Obvously this cannot work if you have 4 stocks, please read the theory before plugging numbers
